


=pod

=head1 NAME - StateMachine::EventAdapter::ContextSubscriber

An Object that subscribes to an Interface Provider based on contextual data in that Object

=head1 EXAMPLE


    my $ContextSubscriber = $ContextSubscriber->new();   # stub example .... expand
                                                

=cut

# This file was automatically generated from ContextSubscriber.pm.m80 by 
# bret on ubuntu (Linux ubuntu 2.6.31-19-generic-pae #56-Ubuntu SMP Thu Jan 28 02:29:51 UTC 2010 i686 GNU/Linux)
# DO NOT EDIT THIS FILE 


package StateMachine::EventAdapter::ContextSubscriber;

use Carp;
use Data::Dumper;
use Term::ANSIColor qw(:constants);
use strict;
sub Confess (@) {confess BOLD, RED, @_, RESET}
sub Warn (@) { warn YELLOW, BOLD, ON_BLACK, @_, RESET }

use File::Basename;

sub printmsg (@) { 
    my $date = localtime;
    print STDERR $date . ":" . basename($0) . ":($$): @_.\n" ;
}

sub printmsgn (@) { 
    my $date = localtime;
    print STDERR $date . ":" . basename($0) . ":($$): @_\n" ;
}

use Utils::FunctionalProgramming;

use base qw(StateMachine::EventAdapter::Subscriber);

=pod

=head1 INHERITANCE

StateMachine::EventAdapter::ContextSubscriber extends class StateMachine::EventAdapter::Subscriber ; refer to the documentation for that object for member variables and methods.

=cut

use fields qw( tag value debug );

=pod

=head1 CONSTRUCTOR

=over 4

=item StateMachine::EventAdapter::ContextSubscriber->new()

initializes on object of type StateMachine::EventAdapter::ContextSubscriber

=back

=cut


# %_allSetters - an array of all setters for all members of the class
my %_allSetters = ();

my %_allMemberAttributes = ();

BEGIN {
# $_allMembers{_TYPE} = 1; # - WHAT IS THIS FOR?
$_allMemberAttributes{tag} = {
          'name' => 'tag',
          'description' => 'The name of a field in a MetaDataObject class. Something like "name" or "ipaddress"'
        }
;
$_allSetters{tag} = \&setTag;
$_allMemberAttributes{value} = {
          'name' => 'value',
          'description' => 'The value that the MetaDataObject field should match successfully in order to dispatch an event to this class. This is a regular expression'
        }
;
$_allSetters{value} = \&setValue;
$_allMemberAttributes{debug} = {
          'name' => 'debug',
          'description' => 'debug allows an object to specify its debugPrint level'
        }
;
$_allSetters{debug} = \&setDebug;


}

#
# TODO ... needs to merge in the parents attributes; the commented out block is close.
#
sub getReflectionAPI { 
#     my $this = shift; 
#     my %unified = (%{$this->SUPER::getReflectionAPI()}, %_allMemberAttributes);
#     \%unified;
    \%_allMemberAttributes;
}

#
# For some (currently) mysterious reason on perl 5.8.8 on the Linux kernel 2.6.18-8.1.14.el5 there
# is no data in the %_allMemberAttributes.  Therefore here is another way to get a list of member data
# out of the class.
#

sub getMembers {
    my $this = shift;
    my @ret = keys(%{$this});
    \@ret;
}
    
sub new {
    my StateMachine::EventAdapter::ContextSubscriber $this = shift;

    print STDERR "in StateMachine::EventAdapter::ContextSubscriber::new(" . join (",", @_) . ")\n" if $ENV{DEBUG};
    Confess "Missing the value for an argument (even nulls) on creation of StateMachine::EventAdapter::ContextSubscriber" if scalar @_ % 2 != 0;

    my %args = @_;

    unless (ref $this) {
	$this = fields::new($this);
    }

    #
    # This next block tries to set any of the values that you passed into this
    # constructor. You might have said new X( arg1 => 123, arg2 => 456); It is going
    # to take that and try to call setArg1(123), setArg2(123). I.e. it is going
    # to derive the setter for your named argument (by upper casing the first letter
    # of your argument name) and then if it finds that the object can call the
    # setter (i.e. it is defined in this class or any parent class) it will call it.
    #
    # If the setter cannot be found - then assume that this is a bad argument
    # that was passed to the function and die with that information.
    #
    foreach my $key (keys(%args)) {

        my $setterName = $key;                              # workspace for determining the name of the setter
        $setterName =~ s/^(\w)/uc($1)/e;                    # uc the first char of the argument name. I.e. arg1 => Arg1.
        $setterName = "set" . $setterName;                  # prepend "set" to the uppercased argument name.

        if (my $fn = $this->UNIVERSAL::can($setterName)) {  # test that the object can call this function
            $fn->($this,$args{$key});                       # and call it
        } else {                                            # else fail with an error. 
            Confess "Field named \"$key\" is not defined in object StateMachine::EventAdapter::ContextSubscriber. typo ?\n";
        }
    }



    #### __new is the magic "pre-constructor".  You can intercept a call to the parent
    #### constructor by defining a __new() procedure in your class.

    eval {StateMachine::EventAdapter::ContextSubscriber::__new($this,%args);};

    croak $@ if $@
	and $@ !~ /^Undefined subroutine.+?StateMachine::EventAdapter::ContextSubscriber::__new/;

    #### Now call the parent constructor, if any.

    eval {$this->SUPER::new(%args)};

    croak $@ if $@
	and $@ !~ /^Can\'t locate object method/;

    ####
    #### Typically this following contains your "real" constructor"
    #### so if you are debugging this next call my be a good candidate to step into.
    ####

    eval {StateMachine::EventAdapter::ContextSubscriber::_new($this,%args);};

    croak $@ if $@
	and $@ !~ /^Undefined subroutine.+?StateMachine::EventAdapter::ContextSubscriber::_new/;

    $this;
}

###  END GENERATED CODE

=pod

=head1 MEMBERS AND MEMBER ACCESS METHODS

=cut



=pod

=head2 tag => "any string"

The name of a field in a MetaDataObject class. Something like "name" or "ipaddress"

=cut

sub getTag {

=pod

=head3 $EventAdapter::ContextSubscriber->getTag ()


getter for member tag

=cut

    my $this = shift;





    return $this->{tag};
}
sub setTag {

=pod

=head3 $EventAdapter::ContextSubscriber->setTag (tag => "any string")

 - tag ("any string")		 : The name of a field in a MetaDataObject class. Something like "name" or "ipaddress"

setter for member tag

=cut

    my $this = shift;


    my $tag = shift;



    $this->{tag} = $tag;
    return $tag;
}



=pod

=head2 value => "any string"

The value that the MetaDataObject field should match successfully in order to dispatch an event to this class. This is a regular expression

=cut

sub getValue {

=pod

=head3 $EventAdapter::ContextSubscriber->getValue ()


getter for member value

=cut

    my $this = shift;





    return $this->{value};
}
sub setValue {

=pod

=head3 $EventAdapter::ContextSubscriber->setValue (value => "any string")

 - value ("any string")		 : The value that the MetaDataObject field should match successfully in order to dispatch an event to this class. This is a regular expression

setter for member value

=cut

    my $this = shift;


    my $value = shift;



    $this->{value} = $value;
    return $value;
}



=pod

=head2 debug => "any string"

debug allows an object to specify its debugPrint level

=cut

sub getDebug {

=pod

=head3 $EventAdapter::ContextSubscriber->getDebug ()


getter for member debug

=cut

    my $this = shift;





    return $this->{debug};
}
sub setDebug {

=pod

=head3 $EventAdapter::ContextSubscriber->setDebug (debug => "any string")

 - debug ("any string")		 : debug allows an object to specify its debugPrint level

setter for member debug

=cut

    my $this = shift;


    my $debug = shift;



    $this->{debug} = $debug;
    return $debug;
}



=pod

=head1 GENERALIZED OBJECT METHODS 

=cut



=pod

=over 4

=item _require (member1,member2,...,memberN)

will iterate over arguments and validate there is a non null value for each of the listed object members

=back

=cut


sub _require
{
    my $this = shift;
    map { 
	Confess "required member variable $_ not set" unless $this->getProperty($_);
    } (@_);
}

sub debugPrint { 
    my $this = shift;
    my $level = shift;
    Confess 'you\'ve called debugPrint - convert this call to $this->debugPrint()'
	unless ref($this);
    if ($this->{debug} >= $level || $main::debug >= $level) {
        my ($caller) = (caller(1))[3];
        $caller = "[$caller]:" if $caller;
        my $date = localtime;
        print STDERR $caller . $date . ":" . basename($0) . ":($$): @_.\n" ;
    }
}

sub debugPrint_s {   # static version of debug print
    my $level = shift;
    if ($main::debug >= $level) {
        my ($caller) = (caller(1))[3];
        $caller = "[$caller]:" if $caller;
        my $date = localtime;
        print STDERR $caller . $date . ":" . basename($0) . ":($$): @_.\n" ;
    }
}

use Carp;

sub docmdq (@) {    
    system(@_);

    my $rc;
    if ($? == -1) {
        $rc = -1; printmsg "failed to execute: $!";
	exit -1;
    }
    elsif ($? & 127) {
        $rc = $? & 127;
        printmsg "child process died with signal $rc, ", ($? & 128) ? 'with' : 'without', " coredump";
	exit $rc;
    }
    else {
        $rc = $? >> 8;
        if ($rc) {
            printmsg "child process exited with value $rc - Exiting!";
            exit $rc;
        }
    }
}

sub docmd (@) {    
    printmsg "@_" ;
    docmdq(@_);
}

1;

=pod

=head1 NOTES ON THIS DOCUMENTATION

In method signatures a * denotes a required option.

This file was automatically generated from ContextSubscriber.pm.m80 by 
bret on ubuntu (Linux ubuntu 2.6.31-19-generic-pae #56-Ubuntu SMP Thu Jan 28 02:29:51 UTC 2010 i686 GNU/Linux)


=head1 OBJECT METHODS

=cut



sub _new {

=pod

=head3 $EventAdapter::ContextSubscriber->_new ()


callback constructor, do not call directly use new() instead

=cut

    my $this = shift;

    Confess "StateMachine::EventAdapter::ContextSubscriber->_new requires named arguments, or maybe a non-static method is being called in a static context " if scalar @_ && scalar @_ % 2 != 0;
    my %args = @_;



    do {
	$this->setObjectType($this->getXmlhash()->{object});
        $this->setTag($this->getXmlhash()->{tag});
        $this->setValue($this->getXmlhash()->{value});
	$this->setHint($this->getXmlhash()->{hint}) if $this->getXmlhash()->{hint};
    };

}

sub getObjects {
    
=pod

=head3 $EventAdapter::ContextSubscriber->getObjects (allObjects => ARRAY)

 - allObjects (ARRAY)		 : A reference to the @allObjects memory space for the current running StateMachine task

Implementation of the StateMachine::EventAdapter::Subscriber interface

=cut

    my $this = shift;

    Confess "StateMachine::EventAdapter::ContextSubscriber->getObjects requires named arguments, or maybe a non-static method is being called in a static context " if scalar @_ && scalar @_ % 2 != 0;
    my %args = @_;
    my $allObjects = $args{allObjects};
        if (defined $allObjects) { Confess "argument 'allObjects' of method StateMachine::EventAdapter::ContextSubscriber->getObjects() is required to be of reference type ARRAY " unless ref($allObjects) =~ /^ARRAY/;}




    # now fetch all objects that match
    return getObjectsByKey( type => $this->getObjectType,                       # implemented in FunctionalProgramming.pm
                            key  => $this->getTag,
                            match => $this->getValue,
                            list => $allObjects );
}

	    

