


=pod

=head1 NAME - StateMachine::EventAdapter::Provider

A State Machine Provider Module

=head1 EXAMPLE


    my $SimpleSubscriber = $SimpleSubscriber->new();   # stub example .... expand


=cut

# This file was automatically generated from Provider.pm.m80 by 
# bret on ubuntu (Linux ubuntu 2.6.31-19-generic-pae #56-Ubuntu SMP Thu Jan 28 02:29:51 UTC 2010 i686 GNU/Linux)
# DO NOT EDIT THIS FILE 


package StateMachine::EventAdapter::Provider;

use Carp;
use Data::Dumper;
use Term::ANSIColor qw(:constants);
use strict;
sub Confess (@) {confess BOLD, RED, @_, RESET}
sub Warn (@) { warn YELLOW, BOLD, ON_BLACK, @_, RESET }

use File::Basename;

sub printmsg (@) { 
    my $date = localtime;
    print STDERR $date . ":" . basename($0) . ":($$): @_.\n" ;
}

sub printmsgn (@) { 
    my $date = localtime;
    print STDERR $date . ":" . basename($0) . ":($$): @_\n" ;
}

use StateMachine::EventAdapter::SimpleSubscriber;
use StateMachine::EventAdapter::ContextSubscriber;
use StateMachine::EventAdapter::ThisIsOfTypeSubscriber;
use fields qw( xmlhash simpleSubscribers contextSubscribers thisIsOfTypeSubscribers module debug );

=pod

=head1 CONSTRUCTOR

=over 4

=item StateMachine::EventAdapter::Provider->new()

initializes on object of type StateMachine::EventAdapter::Provider

=back

=cut


# %_allSetters - an array of all setters for all members of the class
my %_allSetters = ();

my %_allMemberAttributes = ();

BEGIN {
# $_allMembers{_TYPE} = 1; # - WHAT IS THIS FOR?
$_allMemberAttributes{xmlhash} = {
          'required' => 1,
          'ref' => 'HASH',
          'name' => 'xmlhash',
          'description' => 'The parsed interface block from the XML config file.'
        }
;
$_allSetters{xmlhash} = \&setXmlhash;
$_allMemberAttributes{simpleSubscribers} = {
          'ref' => 'HASH',
          'name' => 'simpleSubscribers',
          'description' => 'Hash of SimpleSubscriber objects keyed by object name'
        }
;
$_allSetters{simpleSubscribers} = \&setSimpleSubscribers;
$_allMemberAttributes{contextSubscribers} = {
          'ref' => 'HASH',
          'name' => 'contextSubscribers',
          'description' => 'Hash of ContextSubscriber objects keyed by object name'
        }
;
$_allSetters{contextSubscribers} = \&setContextSubscribers;
$_allMemberAttributes{thisIsOfTypeSubscribers} = {
          'ref' => 'HASH',
          'name' => 'thisIsOfTypeSubscribers',
          'description' => 'Hash of ThisIsOfTypeSubscriber objects keyed by object name'
        }
;
$_allSetters{thisIsOfTypeSubscribers} = \&setThisIsOfTypeSubscribers;
$_allMemberAttributes{module} = {
          'name' => 'module',
          'description' => 'Name of the module that represents this provider'
        }
;
$_allSetters{module} = \&setModule;
$_allMemberAttributes{debug} = {
          'name' => 'debug',
          'description' => 'debug allows an object to specify its debugPrint level'
        }
;
$_allSetters{debug} = \&setDebug;


}

#
# TODO ... needs to merge in the parents attributes; the commented out block is close.
#
sub getReflectionAPI { 
#     my $this = shift; 
#     my %unified = (%{$this->SUPER::getReflectionAPI()}, %_allMemberAttributes);
#     \%unified;
    \%_allMemberAttributes;
}

#
# For some (currently) mysterious reason on perl 5.8.8 on the Linux kernel 2.6.18-8.1.14.el5 there
# is no data in the %_allMemberAttributes.  Therefore here is another way to get a list of member data
# out of the class.
#

sub getMembers {
    my $this = shift;
    my @ret = keys(%{$this});
    \@ret;
}
    
sub new {
    my StateMachine::EventAdapter::Provider $this = shift;

    print STDERR "in StateMachine::EventAdapter::Provider::new(" . join (",", @_) . ")\n" if $ENV{DEBUG};
    Confess "Missing the value for an argument (even nulls) on creation of StateMachine::EventAdapter::Provider" if scalar @_ % 2 != 0;

    my %args = @_;

    unless (ref $this) {
	$this = fields::new($this);
    }

    #
    # This next block tries to set any of the values that you passed into this
    # constructor. You might have said new X( arg1 => 123, arg2 => 456); It is going
    # to take that and try to call setArg1(123), setArg2(123). I.e. it is going
    # to derive the setter for your named argument (by upper casing the first letter
    # of your argument name) and then if it finds that the object can call the
    # setter (i.e. it is defined in this class or any parent class) it will call it.
    #
    # If the setter cannot be found - then assume that this is a bad argument
    # that was passed to the function and die with that information.
    #
    foreach my $key (keys(%args)) {

        my $setterName = $key;                              # workspace for determining the name of the setter
        $setterName =~ s/^(\w)/uc($1)/e;                    # uc the first char of the argument name. I.e. arg1 => Arg1.
        $setterName = "set" . $setterName;                  # prepend "set" to the uppercased argument name.

        if (my $fn = $this->UNIVERSAL::can($setterName)) {  # test that the object can call this function
            $fn->($this,$args{$key});                       # and call it
        } else {                                            # else fail with an error. 
            Confess "Field named \"$key\" is not defined in object StateMachine::EventAdapter::Provider. typo ?\n";
        }
    }


    Confess "cannot initialize object of type StateMachine::EventAdapter::Provider without required member variable xmlhash"
        unless exists $this->{xmlhash};


    #### __new is the magic "pre-constructor".  You can intercept a call to the parent
    #### constructor by defining a __new() procedure in your class.

    eval {StateMachine::EventAdapter::Provider::__new($this,%args);};

    croak $@ if $@
	and $@ !~ /^Undefined subroutine.+?StateMachine::EventAdapter::Provider::__new/;

    #### Now call the parent constructor, if any.

    eval {$this->SUPER::new(%args)};

    croak $@ if $@
	and $@ !~ /^Can\'t locate object method/;

    ####
    #### Typically this following contains your "real" constructor"
    #### so if you are debugging this next call my be a good candidate to step into.
    ####

    eval {StateMachine::EventAdapter::Provider::_new($this,%args);};

    croak $@ if $@
	and $@ !~ /^Undefined subroutine.+?StateMachine::EventAdapter::Provider::_new/;

    $this;
}

###  END GENERATED CODE

=pod

=head1 MEMBERS AND MEMBER ACCESS METHODS

=cut



=pod

=head2 xmlhash => HASH*

The parsed interface block from the XML config file.

=cut

sub getXmlhash {

=pod

=head3 $EventAdapter::Provider->getXmlhash ()


getter for member xmlhash

=cut

    my $this = shift;





    return $this->{xmlhash};
}
sub setXmlhash {

=pod

=head3 $EventAdapter::Provider->setXmlhash (xmlhash => HASH*)

 - xmlhash (HASH)		 : The parsed interface block from the XML config file.

setter for member xmlhash

=cut

    my $this = shift;


    my $xmlhash = shift;
    Confess "argument 'xmlhash' is required for StateMachine::EventAdapter::Provider->setXmlhash()" unless defined $xmlhash;
        if (defined $xmlhash) { Confess "argument 'xmlhash' of method StateMachine::EventAdapter::Provider->setXmlhash() is required to be of reference type HASH " unless ref($xmlhash) =~ /^HASH/;}



    $this->{xmlhash} = $xmlhash;
    return $xmlhash;
}



=pod

=head2 simpleSubscribers => HASH

Hash of SimpleSubscriber objects keyed by object name

=cut

sub getSimpleSubscribers {

=pod

=head3 $EventAdapter::Provider->getSimpleSubscribers ()


getter for member simpleSubscribers

=cut

    my $this = shift;





    return $this->{simpleSubscribers};
}
sub setSimpleSubscribers {

=pod

=head3 $EventAdapter::Provider->setSimpleSubscribers (simpleSubscribers => HASH)

 - simpleSubscribers (HASH)		 : Hash of SimpleSubscriber objects keyed by object name

setter for member simpleSubscribers

=cut

    my $this = shift;


    my $simpleSubscribers = shift;
        if (defined $simpleSubscribers) { Confess "argument 'simpleSubscribers' of method StateMachine::EventAdapter::Provider->setSimpleSubscribers() is required to be of reference type HASH " unless ref($simpleSubscribers) =~ /^HASH/;}



    $this->{simpleSubscribers} = $simpleSubscribers;
    return $simpleSubscribers;
}



=pod

=head2 contextSubscribers => HASH

Hash of ContextSubscriber objects keyed by object name

=cut

sub getContextSubscribers {

=pod

=head3 $EventAdapter::Provider->getContextSubscribers ()


getter for member contextSubscribers

=cut

    my $this = shift;





    return $this->{contextSubscribers};
}
sub setContextSubscribers {

=pod

=head3 $EventAdapter::Provider->setContextSubscribers (contextSubscribers => HASH)

 - contextSubscribers (HASH)		 : Hash of ContextSubscriber objects keyed by object name

setter for member contextSubscribers

=cut

    my $this = shift;


    my $contextSubscribers = shift;
        if (defined $contextSubscribers) { Confess "argument 'contextSubscribers' of method StateMachine::EventAdapter::Provider->setContextSubscribers() is required to be of reference type HASH " unless ref($contextSubscribers) =~ /^HASH/;}



    $this->{contextSubscribers} = $contextSubscribers;
    return $contextSubscribers;
}



=pod

=head2 thisIsOfTypeSubscribers => HASH

Hash of ThisIsOfTypeSubscriber objects keyed by object name

=cut

sub getThisIsOfTypeSubscribers {

=pod

=head3 $EventAdapter::Provider->getThisIsOfTypeSubscribers ()


getter for member thisIsOfTypeSubscribers

=cut

    my $this = shift;





    return $this->{thisIsOfTypeSubscribers};
}
sub setThisIsOfTypeSubscribers {

=pod

=head3 $EventAdapter::Provider->setThisIsOfTypeSubscribers (thisIsOfTypeSubscribers => HASH)

 - thisIsOfTypeSubscribers (HASH)		 : Hash of ThisIsOfTypeSubscriber objects keyed by object name

setter for member thisIsOfTypeSubscribers

=cut

    my $this = shift;


    my $thisIsOfTypeSubscribers = shift;
        if (defined $thisIsOfTypeSubscribers) { Confess "argument 'thisIsOfTypeSubscribers' of method StateMachine::EventAdapter::Provider->setThisIsOfTypeSubscribers() is required to be of reference type HASH " unless ref($thisIsOfTypeSubscribers) =~ /^HASH/;}



    $this->{thisIsOfTypeSubscribers} = $thisIsOfTypeSubscribers;
    return $thisIsOfTypeSubscribers;
}



=pod

=head2 module => "any string"

Name of the module that represents this provider

=cut

sub getModule {

=pod

=head3 $EventAdapter::Provider->getModule ()


getter for member module

=cut

    my $this = shift;





    return $this->{module};
}
sub setModule {

=pod

=head3 $EventAdapter::Provider->setModule (module => "any string")

 - module ("any string")		 : Name of the module that represents this provider

setter for member module

=cut

    my $this = shift;


    my $module = shift;



    $this->{module} = $module;
    return $module;
}



=pod

=head2 debug => "any string"

debug allows an object to specify its debugPrint level

=cut

sub getDebug {

=pod

=head3 $EventAdapter::Provider->getDebug ()


getter for member debug

=cut

    my $this = shift;





    return $this->{debug};
}
sub setDebug {

=pod

=head3 $EventAdapter::Provider->setDebug (debug => "any string")

 - debug ("any string")		 : debug allows an object to specify its debugPrint level

setter for member debug

=cut

    my $this = shift;


    my $debug = shift;



    $this->{debug} = $debug;
    return $debug;
}



=pod

=head1 GENERALIZED OBJECT METHODS 

=cut



=pod

=over 4

=item _require (member1,member2,...,memberN)

will iterate over arguments and validate there is a non null value for each of the listed object members

=back

=cut


sub _require
{
    my $this = shift;
    map { 
	Confess "required member variable $_ not set" unless $this->getProperty($_);
    } (@_);
}

sub debugPrint { 
    my $this = shift;
    my $level = shift;
    Confess 'you\'ve called debugPrint - convert this call to $this->debugPrint()'
	unless ref($this);
    if ($this->{debug} >= $level || $main::debug >= $level) {
        my ($caller) = (caller(1))[3];
        $caller = "[$caller]:" if $caller;
        my $date = localtime;
        print STDERR $caller . $date . ":" . basename($0) . ":($$): @_.\n" ;
    }
}

sub debugPrint_s {   # static version of debug print
    my $level = shift;
    if ($main::debug >= $level) {
        my ($caller) = (caller(1))[3];
        $caller = "[$caller]:" if $caller;
        my $date = localtime;
        print STDERR $caller . $date . ":" . basename($0) . ":($$): @_.\n" ;
    }
}

use Carp;

sub docmdq (@) {    
    system(@_);

    my $rc;
    if ($? == -1) {
        $rc = -1; printmsg "failed to execute: $!";
	exit -1;
    }
    elsif ($? & 127) {
        $rc = $? & 127;
        printmsg "child process died with signal $rc, ", ($? & 128) ? 'with' : 'without', " coredump";
	exit $rc;
    }
    else {
        $rc = $? >> 8;
        if ($rc) {
            printmsg "child process exited with value $rc - Exiting!";
            exit $rc;
        }
    }
}

sub docmd (@) {    
    printmsg "@_" ;
    docmdq(@_);
}

1;

=pod

=head1 NOTES ON THIS DOCUMENTATION

In method signatures a * denotes a required option.

This file was automatically generated from Provider.pm.m80 by 
bret on ubuntu (Linux ubuntu 2.6.31-19-generic-pae #56-Ubuntu SMP Thu Jan 28 02:29:51 UTC 2010 i686 GNU/Linux)


=head1 OBJECT METHODS

=cut



sub _new {

=pod

=head3 $EventAdapter::Provider->_new ()


callback constructor, do not call directly use new() instead

=cut

    my $this = shift;

    Confess "StateMachine::EventAdapter::Provider->_new requires named arguments, or maybe a non-static method is being called in a static context " if scalar @_ && scalar @_ % 2 != 0;
    my %args = @_;




    do { 
	my $xml = $this->getXmlhash();
	$this->setModule($xml->{module});

        #
        # load all the SimpleSubscriber Objects
	my @simpleSubscribers;
	eval {
	    @simpleSubscribers = @{$xml->{'simple-subscribers'}[0]->{'simple-subscriber'}};
	};
	unless ($@) {                                                           # the XML access could fail if no simple-subscribers were defined in the XML document
	    my $simpleSubscribersHash = {};

	    foreach my $simpleSubscriber (@simpleSubscribers) {
		my $SimpleSubscriber = StateMachine::EventAdapter::SimpleSubscriber->new(xmlhash => $simpleSubscriber);
		$simpleSubscribersHash->{$simpleSubscriber->{object}} = $SimpleSubscriber;
	    }

	    $this->setSimpleSubscribers($simpleSubscribersHash);
	}


        #
        # load all the ContextSubscriber Objects
	my @contextSubscribers;
	eval {
	    @contextSubscribers = @{$xml->{'context-subscribers'}[0]->{'context-subscriber'}};
	};
	unless ($@) {                                                           # the XML access could fail if no simple-subscribers were defined in the XML document
	    my $contextSubscribersHash = {};

	    foreach my $contextSubscriber (@contextSubscribers) {
		my $ContextSubscriber = StateMachine::EventAdapter::ContextSubscriber->new(xmlhash => $contextSubscriber);
		$contextSubscribersHash->{$contextSubscriber->{object}} = $ContextSubscriber;
	    }

	    $this->setContextSubscribers($contextSubscribersHash);
	}


        #
        # load all the ThisIsOfTypeSubscriber Objects
	my @thisIsOfTypeSubscribers;
	eval {
	    @thisIsOfTypeSubscribers = @{$xml->{'thisisoftype-subscribers'}[0]->{'thisisoftype-subscriber'}};
	};
	unless ($@) {                                                           # the XML access could fail if no thisisoftype-subscribers were defined in the XML document
	    my $thisIsOfTypeSubscribersHash = {};

	    foreach my $thisIsOfTypeSubscriber (@thisIsOfTypeSubscribers) {
		my $ThisIsOfTypeSubscriber = StateMachine::EventAdapter::ThisIsOfTypeSubscriber->new(xmlhash => $thisIsOfTypeSubscriber);
		$thisIsOfTypeSubscribersHash->{$ThisIsOfTypeSubscriber->getObjectType} = $ThisIsOfTypeSubscriber;
	    }

	    $this->setThisIsOfTypeSubscribers($thisIsOfTypeSubscribersHash);
	}

    };
}
