$ScopedActions1 = {
                    'IntervalETLManagerImpl-loopSuccess' => '1',
                    'ReplicationETLImpl-crawl' => '1',
                    'ETLManager-stop' => '1',
                    'SugarETLManagerImpl-dependency_SugarETLRunLoop_work' => '1',
                    'PollingETLManagerImpl-loopSuccess' => '1',
                    'DimensionalETLImpl-extract' => '1',
                    'ETLPostProcessors-WBSSolorWindsPostProcess' => '1',
                    'BaseETLManagerImpl-run' => '1',
                    'ARReplicationETLImpl-extract' => '1',
                    'SugarETLManagerImpl-SugarETLRunLoop' => '1',
                    'ARReplicationETLImpl-stage' => '1',
                    'PollingETLManagerImpl-loopFailure' => '1',
                    'ETLManager-run' => '1',
                    'ETL-transform' => '1',
                    'SugarETLManagerImpl-SugarETLLoop_parent' => '1',
                    'IntervalETLManagerImpl-IntervalETLRunLoop_work' => '1',
                    'PollingETLManagerImpl-PollingETLRunLoop_work' => '1',
                    'PollingETLManagerImpl-PollingETLRunLoop' => '1',
                    'ReplicationETLImpl-load' => '1',
                    'ARReplicationETLImpl-load' => '1',
                    'ETL-extract' => '1',
                    'ReplicationETLImpl-stage' => '1',
                    'IntervalETLManagerImpl-run' => '1',
                    'PollingETLManagerImpl-dependency_PollingETLRunLoop_work' => '1',
                    'SugarETLManagerImpl-loopSuccess' => '1',
                    'SugarETLManagerImpl-SugarETLRunLoop_work' => '1',
                    'DimensionalETLImpl-dependency_extract' => '1',
                    'PollingETLManagerImpl-run' => '1',
                    'ETL-crawl' => '1',
                    'IntervalETLManagerImpl-dependency_IntervalETLRunLoop_work' => '1',
                    'StateMachineBase-initialize' => '1',
                    'ReplicationETLImpl-extract' => '1',
                    'ETL-postprocess' => '1',
                    'ARReplicationETLImpl-transform' => '1',
                    'SugarETLManagerImpl-run' => '1',
                    'IntervalETLManagerImpl-IntervalETLRunLoop' => '1',
                    'ETL-load' => '1',
                    'ReplicationETLImpl-transform' => '1',
                    'SugarETLManagerImpl-loopFailure' => '1',
                    'PollingETLManagerImpl-PollingETLLoop_parent' => '1',
                    'ETL-stage' => '1',
                    'BaseETLManagerImpl-dependency_run' => '1',
                    'IntervalETLManagerImpl-IntervalETLLoop_parent' => '1',
                    'IntervalETLManagerImpl-loopFailure' => '1'
                  };


1;

