
  

=pod

=head1 NAME - JRockit::HeapDiagnostics

Object Built from the output of 
jrcmd <java pid> heap_diagnostics


=head1 EXAMPLE


    my $HeapDiagnostics = $HeapDiagnostics->new();   # stub example .... expand


=cut

# This file was automatically generated from HeapDiagnostics.pm.m80 by 
# bret on ubuntu (Linux ubuntu 2.6.31-19-generic-pae #56-Ubuntu SMP Thu Jan 28 02:29:51 UTC 2010 i686 GNU/Linux)
# DO NOT EDIT THIS FILE 


package JRockit::HeapDiagnostics;

use Carp;
use Data::Dumper;
use Term::ANSIColor qw(:constants);
use strict;
sub Confess (@) {confess BOLD, RED, @_, RESET}
sub Warn (@) { warn YELLOW, BOLD, ON_BLACK, @_, RESET }

use File::Basename;

sub printmsg (@) { 
    my $date = localtime;
    print STDERR $date . ":" . basename($0) . ":($$): @_.\n" ;
}

sub printmsgn (@) { 
    my $date = localtime;
    print STDERR $date . ":" . basename($0) . ":($$): @_\n" ;
}

use JRockit::HeapStatistic;
use fields qw( filename heapClassStats sortedOrder debug );

=pod

=head1 CONSTRUCTOR

=over 4

=item JRockit::HeapDiagnostics->new()

initializes on object of type JRockit::HeapDiagnostics

=back

=cut


# %_allSetters - an array of all setters for all members of the class
my %_allSetters = ();

my %_allMemberAttributes = ();

BEGIN {
# $_allMembers{_TYPE} = 1; # - WHAT IS THIS FOR?
$_allMemberAttributes{filename} = {
          'required' => 1,
          'name' => 'filename',
          'type' => 'string',
          'description' => 'Name of the heap_diagnostics output file'
        }
;
$_allSetters{filename} = \&setFilename;
$_allMemberAttributes{heapClassStats} = {
          'ref' => 'HASH',
          'name' => 'heapClassStats',
          'description' => 'Hash of stats on classes in the heap'
        }
;
$_allSetters{heapClassStats} = \&setHeapClassStats;
$_allMemberAttributes{sortedOrder} = {
          'ref' => 'ARRAY',
          'name' => 'sortedOrder',
          'description' => 'HeapStatistics sorted by size'
        }
;
$_allSetters{sortedOrder} = \&setSortedOrder;
$_allMemberAttributes{debug} = {
          'name' => 'debug',
          'description' => 'debug allows an object to specify its debugPrint level'
        }
;
$_allSetters{debug} = \&setDebug;


}

#
# TODO ... needs to merge in the parents attributes; the commented out block is close.
#
sub getReflectionAPI { 
#     my $this = shift; 
#     my %unified = (%{$this->SUPER::getReflectionAPI()}, %_allMemberAttributes);
#     \%unified;
    \%_allMemberAttributes;
}

#
# For some (currently) mysterious reason on perl 5.8.8 on the Linux kernel 2.6.18-8.1.14.el5 there
# is no data in the %_allMemberAttributes.  Therefore here is another way to get a list of member data
# out of the class.
#

sub getMembers {
    my $this = shift;
    my @ret = keys(%{$this});
    \@ret;
}
    
sub new {
    my JRockit::HeapDiagnostics $this = shift;

    print STDERR "in JRockit::HeapDiagnostics::new(" . join (",", @_) . ")\n" if $ENV{DEBUG};
    Confess "Missing the value for an argument (even nulls) on creation of JRockit::HeapDiagnostics" if scalar @_ % 2 != 0;

    my %args = @_;

    unless (ref $this) {
	$this = fields::new($this);
    }

    #
    # This next block tries to set any of the values that you passed into this
    # constructor. You might have said new X( arg1 => 123, arg2 => 456); It is going
    # to take that and try to call setArg1(123), setArg2(123). I.e. it is going
    # to derive the setter for your named argument (by upper casing the first letter
    # of your argument name) and then if it finds that the object can call the
    # setter (i.e. it is defined in this class or any parent class) it will call it.
    #
    # If the setter cannot be found - then assume that this is a bad argument
    # that was passed to the function and die with that information.
    #
    foreach my $key (keys(%args)) {

        my $setterName = $key;                              # workspace for determining the name of the setter
        $setterName =~ s/^(\w)/uc($1)/e;                    # uc the first char of the argument name. I.e. arg1 => Arg1.
        $setterName = "set" . $setterName;                  # prepend "set" to the uppercased argument name.

        if (my $fn = $this->UNIVERSAL::can($setterName)) {  # test that the object can call this function
            $fn->($this,$args{$key});                       # and call it
        } else {                                            # else fail with an error. 
            Confess "Field named \"$key\" is not defined in object JRockit::HeapDiagnostics. typo ?\n";
        }
    }


    Confess "cannot initialize object of type JRockit::HeapDiagnostics without required member variable filename"
        unless exists $this->{filename};


    #### __new is the magic "pre-constructor".  You can intercept a call to the parent
    #### constructor by defining a __new() procedure in your class.

    eval {JRockit::HeapDiagnostics::__new($this,%args);};

    croak $@ if $@
	and $@ !~ /^Undefined subroutine.+?JRockit::HeapDiagnostics::__new/;

    #### Now call the parent constructor, if any.

    eval {$this->SUPER::new(%args)};

    croak $@ if $@
	and $@ !~ /^Can\'t locate object method/;

    ####
    #### Typically this following contains your "real" constructor"
    #### so if you are debugging this next call my be a good candidate to step into.
    ####

    eval {JRockit::HeapDiagnostics::_new($this,%args);};

    croak $@ if $@
	and $@ !~ /^Undefined subroutine.+?JRockit::HeapDiagnostics::_new/;

    $this;
}

###  END GENERATED CODE

=pod

=head1 MEMBERS AND MEMBER ACCESS METHODS

=cut



=pod

=head2 filename => "any string"*

Name of the heap_diagnostics output file

=cut

sub getFilename {

=pod

=head3 $HeapDiagnostics->getFilename ()


getter for member filename

=cut

    my $this = shift;





    return $this->{filename};
}
sub setFilename {

=pod

=head3 $HeapDiagnostics->setFilename (filename => "any string"*)

 - filename ("any string")		 : Name of the heap_diagnostics output file

setter for member filename

=cut

    my $this = shift;


    my $filename = shift;
    Confess "argument 'filename' is required for JRockit::HeapDiagnostics->setFilename()" unless defined $filename;



    $this->{filename} = $filename;
    return $filename;
}



=pod

=head2 heapClassStats => HASH

Hash of stats on classes in the heap

=cut

sub getHeapClassStats {

=pod

=head3 $HeapDiagnostics->getHeapClassStats ()


getter for member heapClassStats

=cut

    my $this = shift;





    return $this->{heapClassStats};
}
sub setHeapClassStats {

=pod

=head3 $HeapDiagnostics->setHeapClassStats (heapClassStats => HASH)

 - heapClassStats (HASH)		 : Hash of stats on classes in the heap

setter for member heapClassStats

=cut

    my $this = shift;


    my $heapClassStats = shift;
        if (defined $heapClassStats) { Confess "argument 'heapClassStats' of method JRockit::HeapDiagnostics->setHeapClassStats() is required to be of reference type HASH " unless ref($heapClassStats) =~ /^HASH/;}



    $this->{heapClassStats} = $heapClassStats;
    return $heapClassStats;
}



=pod

=head2 sortedOrder => ARRAY

HeapStatistics sorted by size

=cut

sub getSortedOrder {

=pod

=head3 $HeapDiagnostics->getSortedOrder ()


getter for member sortedOrder

=cut

    my $this = shift;





    return $this->{sortedOrder};
}
sub setSortedOrder {

=pod

=head3 $HeapDiagnostics->setSortedOrder (sortedOrder => ARRAY)

 - sortedOrder (ARRAY)		 : HeapStatistics sorted by size

setter for member sortedOrder

=cut

    my $this = shift;


    my $sortedOrder = shift;
        if (defined $sortedOrder) { Confess "argument 'sortedOrder' of method JRockit::HeapDiagnostics->setSortedOrder() is required to be of reference type ARRAY " unless ref($sortedOrder) =~ /^ARRAY/;}



    $this->{sortedOrder} = $sortedOrder;
    return $sortedOrder;
}



=pod

=head2 debug => "any string"

debug allows an object to specify its debugPrint level

=cut

sub getDebug {

=pod

=head3 $HeapDiagnostics->getDebug ()


getter for member debug

=cut

    my $this = shift;





    return $this->{debug};
}
sub setDebug {

=pod

=head3 $HeapDiagnostics->setDebug (debug => "any string")

 - debug ("any string")		 : debug allows an object to specify its debugPrint level

setter for member debug

=cut

    my $this = shift;


    my $debug = shift;



    $this->{debug} = $debug;
    return $debug;
}



=pod

=head1 GENERALIZED OBJECT METHODS 

=cut



=pod

=over 4

=item _require (member1,member2,...,memberN)

will iterate over arguments and validate there is a non null value for each of the listed object members

=back

=cut


sub _require
{
    my $this = shift;
    map { 
	Confess "required member variable $_ not set" unless $this->getProperty($_);
    } (@_);
}

sub debugPrint { 
    my $this = shift;
    my $level = shift;
    Confess 'you\'ve called debugPrint - convert this call to $this->debugPrint()'
	unless ref($this);
    if ($this->{debug} >= $level || $main::debug >= $level) {
        my ($caller) = (caller(1))[3];
        $caller = "[$caller]:" if $caller;
        my $date = localtime;
        print STDERR $caller . $date . ":" . basename($0) . ":($$): @_.\n" ;
    }
}

sub debugPrint_s {   # static version of debug print
    my $level = shift;
    if ($main::debug >= $level) {
        my ($caller) = (caller(1))[3];
        $caller = "[$caller]:" if $caller;
        my $date = localtime;
        print STDERR $caller . $date . ":" . basename($0) . ":($$): @_.\n" ;
    }
}

use Carp;

sub docmdq (@) {    
    system(@_);

    my $rc;
    if ($? == -1) {
        $rc = -1; printmsg "failed to execute: $!";
	exit -1;
    }
    elsif ($? & 127) {
        $rc = $? & 127;
        printmsg "child process died with signal $rc, ", ($? & 128) ? 'with' : 'without', " coredump";
	exit $rc;
    }
    else {
        $rc = $? >> 8;
        if ($rc) {
            printmsg "child process exited with value $rc - Exiting!";
            exit $rc;
        }
    }
}

sub docmd (@) {    
    printmsg "@_" ;
    docmdq(@_);
}

1;

=pod

=head1 NOTES ON THIS DOCUMENTATION

In method signatures a * denotes a required option.

This file was automatically generated from HeapDiagnostics.pm.m80 by 
bret on ubuntu (Linux ubuntu 2.6.31-19-generic-pae #56-Ubuntu SMP Thu Jan 28 02:29:51 UTC 2010 i686 GNU/Linux)


=head1 OBJECT METHODS

=cut



sub _new {
  
=pod

=head3 $HeapDiagnostics->_new ()


callback constructor, do not call directly use new() instead

=cut

    my $this = shift;

    Confess "JRockit::HeapDiagnostics->_new requires named arguments, or maybe a non-static method is being called in a static context " if scalar @_ && scalar @_ % 2 != 0;
    my %args = @_;



  do {
      my %heapClassStats = ();
      $this->setHeapClassStats( \%heapClassStats );

      my @sortedOrder = ();
      $this->setSortedOrder( \@sortedOrder);

      open FILE, "< " . $this->getFilename();

      my $readState = "INITIAL";
      while (<FILE>) {
	  my $line = $_;
	  if (/--------- Detailed Heap Statistics: ---------/) {
	      $readState = 'DETAILED HEAP STATISTICS';
	      next;
	  }

	  if ($readState =~ /DETAILED/) {
	      if ($line =~ /total ---/) {
		  $readState = "UNKNOWN";
	      } else {
#		  $line =~ /(\d+\.\d+%) (\d+k)\s+(\d+)\s+[+\-](d+)k (.+)/;
		  $line =~ /(\d+\.\d+%) (\d+)\w\s+(\d+)\s+([\+\-]\d+k) (.+)/;

		  my $_hs = new JRockit::HeapStatistic (percentage => $1,
							totalSize => $2,
							numInstances => $3,
							delta => $4,
							name => $5);
		  $heapClassStats{$5} = $_hs;
		  push (@sortedOrder, $_hs);
	      }
	  }

      }

      close FILE;
  };
}

#sub method {
# remove the spaces from the tag below
#    < : = $po->contract('method' => {description => "method description"} ); :>
#}
	    

